config/routes.rb
Rails.application.routes.draw do
  resources :locals
  root 'home#home'
  get 'form' => 'form#form'
  get 'welcome' => 'home#home'
  get 'about' => 'about#about'
  get 'help' => 'help#help'
  get 'contact' => 'contact#contact'
  post 'sugestao' => 'sugestao#sugestao'
  get 'descricao' => 'descricao#descricao'

  end

app/models/bus.rb
class Bus < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base

end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
end

app/models/museu.rb
class Museu < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/form_controller.rb
class FormController < ApplicationController

	def form
	end

	def demo_form
	end

end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end

end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]

  # GET /locals
  # GET /locals.json
  def index
    @locals = Local.all
  end

  # GET /locals/1
  # GET /locals/1.json
  def show
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1
  # PATCH/PUT /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locals_url, notice: 'Local was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit(:nome, :descricao, :logradouro, :bairro, :tipo, :animacao, :interacao, :faixaEtaria, :longitude, :latitude, :imagem, :nota, :cod_linha, :preco, :telefone, :site, :horario_abre, :horario_fecha)
    end
end

app/controllers/lugars_controller.rb
class LugarsController < ApplicationController
  before_action :set_lugar, only: [:show, :edit, :update, :destroy]

  # GET /lugars
  # GET /lugars.json
  def index
    @lugars = Lugar.all
  end

  # GET /lugars/1
  # GET /lugars/1.json
  def show
  end

  # GET /lugars/new
  def new
    @lugar = Lugar.new
  end

  # GET /lugars/1/edit
  def edit
  end

  # POST /lugars
  # POST /lugars.json
  def create
    @lugar = Lugar.new(lugar_params)

    respond_to do |format|
      if @lugar.save
        format.html { redirect_to @lugar, notice: 'Lugar was successfully created.' }
        format.json { render :show, status: :created, location: @lugar }
      else
        format.html { render :new }
        format.json { render json: @lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lugars/1
  # PATCH/PUT /lugars/1.json
  def update
    respond_to do |format|
      if @lugar.update(lugar_params)
        format.html { redirect_to @lugar, notice: 'Lugar was successfully updated.' }
        format.json { render :show, status: :ok, location: @lugar }
      else
        format.html { render :edit }
        format.json { render json: @lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lugars/1
  # DELETE /lugars/1.json
  def destroy
    @lugar.destroy
    respond_to do |format|
      format.html { redirect_to lugars_url, notice: 'Lugar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lugar
      @lugar = Lugar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lugar_params
      params.require(:lugar).permit(:nome, :descricao, :logradouro, :bairro, :tipo, :animacao, :interacao, :faixaEtaria, :logitude, :latitude, :imagem, :nota, :cod_linha, :preco, :telefone, :site, :horario_abre, :horario_fecha)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def form
	end

	def sugest
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/descricao_helper.rb
module DescricaoHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/popular_helper.rb
module PopularHelper
end

app/helpers/sugestao_helper.rb
module SugestaoHelper
end

app/views/locals/_form.html.erb
<%= form_for(@local) do |f| %>
  <% if @local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% @local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :bairro %><br>
    <%= f.text_field :bairro %>
  </div>
  <div class="field">
    <%= f.label :logradouro %><br>
    <%= f.text_field :logradouro %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :animacao %><br>
    <%= f.text_field :animacao %>
  </div>
  <div class="field">
    <%= f.label :interacao %><br>
    <%= f.text_field :interacao %>
  </div>
  <div class="field">
    <%= f.label :faixaEtaria %><br>
    <%= f.number_field :faixaEtaria %>
  </div>
  <div class="field">
    <%= f.label :imagem %><br>
    <%= f.text_field :imagem %>
  </div>
  <div class="field">
    <%= f.label :nota %><br>
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :cod_linha %><br>
    <%= f.number_field :cod_linha %>
  </div>
  <div class="field">
    <%= f.label :preco %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :horario_abre %><br>
    <%= f.text_field :horario_abre %>
  </div>
  <div class="field">
    <%= f.label :horario_fecha %><br>
    <%= f.text_field :horario_fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locals/edit.html.erb
<h1>Editing Local</h1>

<%= render 'form' %>

<%= link_to 'Show', @local %> |
<%= link_to 'Back', locals_path %>

app/views/locals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locals</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Logradouro</th>
      <th>Bairro</th>
      <th>Tipo</th>
      <th>Animacao</th>
      <th>Interacao</th>
      <th>Faixaetaria</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Imagem</th>
      <th>Nota</th>
      <th>Cod linha</th>
      <th>Preco</th>
      <th>Telefone</th>
      <th>Site</th>
      <th>Horario abre</th>
      <th>Horario fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locals.each do |local| %>
      <tr>
        <td><%= local.nome %></td>
        <td><%= local.descricao %></td>
        <td><%= local.logradouro %></td>
        <td><%= local.bairro %></td>
        <td><%= local.tipo %></td>
        <td><%= local.animacao %></td>
        <td><%= local.interacao %></td>
        <td><%= local.faixaEtaria %></td>
        <td><%= local.longitude %></td>
        <td><%= local.latitude %></td>
        <td><%= local.imagem %></td>
        <td><%= local.nota %></td>
        <td><%= local.cod_linha %></td>
        <td><%= local.preco %></td>
        <td><%= local.telefone %></td>
        <td><%= local.site %></td>
        <td><%= local.horario_abre %></td>
        <td><%= local.horario_fecha %></td>
        <td><%= link_to 'Show', local %></td>
        <td><%= link_to 'Edit', edit_local_path(local) %></td>
        <td><%= link_to 'Destroy', local, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Local', new_local_path %>

app/views/locals/new.html.erb
<h1>New Local</h1>

<%= render 'form' %>

<%= link_to 'Back', locals_path %>

app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @local.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @local.descricao %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @local.logradouro %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @local.bairro %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @local.tipo %>
</p>

<p>
  <strong>Animacao:</strong>
  <%= @local.animacao %>
</p>

<p>
  <strong>Interacao:</strong>
  <%= @local.interacao %>
</p>

<p>
  <strong>Faixaetaria:</strong>
  <%= @local.faixaEtaria %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @local.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @local.latitude %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @local.imagem %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @local.nota %>
</p>

<p>
  <strong>Cod linha:</strong>
  <%= @local.cod_linha %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @local.preco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @local.telefone %>
</p>

<p>
  <strong>Site:</strong>
  <%= @local.site %>
</p>

<p>
  <strong>Horario abre:</strong>
  <%= @local.horario_abre %>
</p>

<p>
  <strong>Horario fecha:</strong>
  <%= @local.horario_fecha %>
</p>

<%= link_to 'Edit', edit_local_path(@local) %> |
<%= link_to 'Back', locals_path %>

app/views/lugars/_form.html.erb
<%= form_for(@lugar) do |f| %>
  <% if @lugar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lugar.errors.count, "error") %> prohibited this lugar from being saved:</h2>

      <ul>
      <% @lugar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :bairro %><br>
    <%= f.text_field :bairro %>
  </div>
  <div class="field">
    <%= f.label :logradouro %><br>
    <%= f.text_field :logradouro %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :animacao %><br>
    <%= f.text_field :animacao %>
  </div>
  <div class="field">
    <%= f.label :interacao %><br>
    <%= f.text_field :interacao %>
  </div>
  <div class="field">
    <%= f.label :faixaEtaria %><br>
    <%= f.number_field :faixaEtaria %>
  </div>
  <div class="field">
    <%= f.label :imagem %><br>
    <%= f.text_field :imagem %>
  </div>
  <div class="field">
    <%= f.label :nota %><br>
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :cod_linha %><br>
    <%= f.number_field :cod_linha %>
  </div>
  <div class="field">
    <%= f.label :preco %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :horario_abre %><br>
    <%= f.text_field :horario_abre %>
  </div>
  <div class="field">
    <%= f.label :horario_fecha %><br>
    <%= f.text_field :horario_fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lugars/edit.html.erb
<h1>Editing Lugar</h1>

<%= render 'form' %>

<%= link_to 'Show', @lugar %> |
<%= link_to 'Back', lugars_path %>

app/views/lugars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lugars</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Logradouro</th>
      <th>Bairro</th>
      <th>Tipo</th>
      <th>Animacao</th>
      <th>Interacao</th>
      <th>Faixaetaria</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Imagem</th>
      <th>Nota</th>
      <th>Cod_Linha</th>
      <th>Preco</th>
      <th>Telefone</th>
      <th>Site</th>
      <th>Horario_Abre</th>
      <th>Horario_Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lugars.each do |lugar| %>
      <tr>
        <td><%= lugar.nome %></td>
        <td><%= lugar.descricao %></td>
        <td><%= lugar.logradouro %></td>
        <td><%= lugar.bairro %></td>
        <td><%= lugar.tipo %></td>
        <td><%= lugar.animacao %></td>
        <td><%= lugar.interacao %></td>
        <td><%= lugar.faixaEtaria %></td>
        <td><%= lugar.longitude %></td>
        <td><%= lugar.latitude %></td>
        <td><%= lugar.imagem %></td>
        <td><%= lugar.nota %></td>
        <td><%= lugar.cod_linha %></td>
        <td><%= lugar.preco %></td>
        <td><%= lugar.telefone %></td>
        <td><%= lugar.site %></td>
        <td><%= lugar.horario_abre %></td>
        <td><%= lugar.horario_fecha %></td>
        <td><%= link_to 'Show', lugar %></td>
        <td><%= link_to 'Edit', edit_lugar_path(lugar) %></td>
        <td><%= link_to 'Destroy', lugar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lugar', new_lugar_path %>

app/views/lugars/new.html.erb
<h1>New Lugar</h1>

<%= render 'form' %>

<%= link_to 'Back', lugars_path %>

app/views/lugars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @lugar.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @lugar.descricao %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @lugar.logradouro %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @lugar.bairro %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @lugar.tipo %>
</p>

<p>
  <strong>Animacao:</strong>
  <%= @lugar.animacao %>
</p>

<p>
  <strong>Interacao:</strong>
  <%= @lugar.interacao %>
</p>

<p>
  <strong>Faixaetaria:</strong>
  <%= @lugar.faixaEtaria %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @lugar.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @lugar.latitude %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @lugar.imagem %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @lugar.nota %>
</p>

<p>
  <strong>Cod_Linha:</strong>
  <%= @lugar.cod_linha %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @lugar.preco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @lugar.telefone %>
</p>

<p>
  <strong>Site:</strong>
  <%= @lugar.site %>
</p>

<p>
  <strong>Horario_Abre:</strong>
  <%= @lugar.horario_abre %>
</p>

<p>
  <strong>Horario_Fecha:</strong>
  <%= @lugar.horario_fecha %>
</p>

<%= link_to 'Edit', edit_lugar_path(@lugar) %> |
<%= link_to 'Back', lugars_path %>