config/routes.rb
Rails.application.routes.draw do
  resources :locals
  root 'home#home'
  get 'form' => 'form#form'
  get 'welcome' => 'home#home'
  get 'about' => 'about#about'
  get 'help' => 'help#help'
  get 'contact' => 'contact#contact'
  post 'sugestao' => 'sugestao#sugestao'
  get 'descricao' => 'descricao#descricao'

  end

app/models/bus.rb
class Bus < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base

end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
end

app/models/museu.rb
class Museu < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/form_controller.rb
class FormController < ApplicationController

	def form
	end

	def demo_form
	end

end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def form
	end

	def sugest
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/descricao_helper.rb
module DescricaoHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/popular_helper.rb
module PopularHelper
end

app/helpers/sugestao_helper.rb
module SugestaoHelper
end

app/views/form/form.html.erb
<div class="row">
 <div class="col-md-6 col-md-offset-3 grid">
<h1><b>FORMULÁRIO</b></h1>
          <p>Preencha o formulário para achar um lugar!</p>
          <br>
          <%= form_tag("sugestao", method: "post") do %>

            <p>Qual sua preferencia quanto ao espirito do local?</p>
            <%= radio_button_tag(:espirito_local, "A") %>
            <%= label_tag("Agitado") %><br>
            <%= radio_button_tag(:espirito_local, "C") %>
            <%= label_tag("Calmo") %><br>
            
            <p>Qual sua preferencia quanto a sua experiência?</p>
            <%= radio_button_tag(:experiencia, "I") %>
            <%= label_tag("Interativo") %><br>
            <%= radio_button_tag(:experiencia, "E") %>
            <%= label_tag("Expositivo") %><br>
            
            <p>Qual tipo de lugar você prefere?</p>
            <%= radio_button_tag(:tipo, "M") %>
            <%= label_tag("Museu") %><br>
            <%= radio_button_tag(:tipo, "T") %>
            <%= label_tag("Teatro") %><br>
            <%= radio_button_tag(:tipo, "S") %>
            <%= label_tag("Shopping") %><br>
            <%= radio_button_tag(:tipo, "MP") %>
            <%= label_tag("Mercados Públicos") %><br>

            <br>
            Horário desejado: (hh:mm)<br>
            <%= text_field_tag(:hora_inicial)%><br><br>
            <%= submit_tag("Submit", id: 'submit') %><br>
          <%end%>
</div>
<br>
<br>
</div>

app/views/home/home.html.erb
<div class="center jumbotron">
	<h1> Não Sei Onde Ir</h1>
	<h2> Descubra lugares de acordo com seu perfil!</h2>
	<%= link_to "Começar", form_path, class: "btn btn-lg btn-primary" %>
</div>