config/routes.rb
Rails.application.routes.draw do
  resources :locals
  root 'home#home'
  get 'form' => 'form#form'
  get 'welcome' => 'home#home'
  get 'about' => 'about#about'
  get 'help' => 'help#help'
  get 'contact' => 'contact#contact'
  post 'sugestao' => 'sugestao#sugestao'
  get 'descricao' => 'descricao#descricao'

  end

app/models/bus.rb
class Bus < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base

end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
end

app/models/museu.rb
class Museu < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/form_controller.rb
class FormController < ApplicationController

	def form
	end

	def demo_form
	end

end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/descricao_helper.rb
module DescricaoHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/popular_helper.rb
module PopularHelper
end

app/helpers/sugestao_helper.rb
module SugestaoHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="footer-below">
        <small>Copyright &copy;NãoSeiOndeIR desenvolvido por USS Enterprise</small>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    	<div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
          </button>
    		  <%= link_to "NSOI", root_path, class: "navbar-brand", id: "logo" %>
        </div>
    		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    			<ul class="nav navbar-nav navbar-right">
    				<li><%= link_to "Início", root_path, :class => "active" %></li>
    				<li><%= link_to "Ajuda", help_path %></li>
            <li><%= link_to "Contato", contact_path %></li>
            <li><%= link_to "Sobre", about_path %></li>
  					<li><%= form_tag("sugestao", method: "post") do %>
            <%= text_field_tag(:valor) %>
            <%= image_submit_tag('http://images.sixrevisions.com/2010/11/17-20_search_png24.png',width: '50', height: '40', id: 'submit', :class => 'btn btn-invert btn-sm') %><br>
            <% end %>
					</li>
    			</ul>
    		</div>
    	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>NSOI</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/1-col-portfolio.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    	<%=yield %>
  </div>
  </body>
</html>